apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: poothon 
  janus-idp.io/tekton: poothon
  backstage.io/kubernetes-id: poothon
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: poothon
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  